routes/web.php
<?php

use App\Http\Controllers\BuilderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::prefix('dynamic-forms')->name('form-builder.')->group(function () {
    // Dummy route so we can use the route() helper to give formiojs the base path for this group
    
    Route::get('/', [BuilderController::class, 'create'])->name('index');
    Route::post('/', [BuilderController::class, 'store'])->name('store');
    Route::get('/render_form', [BuilderController::class, 'renderForm'])->name('render-form');
    Route::post('/render_store', [BuilderController::class, 'formStore'])->name('form_store');

    Route::post('storage/s3', [Controllers\DynamicFormsStorageController::class, 'storeS3'])
        ->withoutMiddleware([\App\Http\Middleware\VerifyCsrfToken::class]);

    Route::get('storage/s3', [Controllers\DynamicFormsStorageController::class, 'showS3'])->name('S3-file-download');
    Route::get('storage/s3/{fileKey}', [Controllers\DynamicFormsStorageController::class, 'showS3'])->name('S3-file-redirect');

    Route::post('storage/url', [Controllers\DynamicFormsStorageController::class, 'storeURL'])
        ->withoutMiddleware([\App\Http\Middleware\VerifyCsrfToken::class]);

    Route::get('storage/url', [Controllers\DynamicFormsStorageController::class, 'showURL'])->name('url-file-download');
    Route::delete('storage/url', [Controllers\DynamicFormsStorageController::class, 'deleteURL']);

    // Route::get('form', [Controllers\ResourceController::class, 'index']);
    // Route::get('form/{resource}', [Controllers\ResourceController::class, 'resource']);
    // Route::get('form/{resource}/submission', [Controllers\ResourceController::class, 'resourceSubmissions']);
});

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    
    @yield('content')
    

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
@stack('js')
</body>
</html>

resources/views/builder.blade.php
<html>
  <head>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdn.form.io/formiojs/formio.full.min.css'>
    <script src='https://cdn.form.io/formiojs/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        new Formio.builder(
            document.getElementById('formio-builder'),
            @if(isset($definition)) {!! $definition !!} @else {} @endif,
            {} // these are the opts you can customize
        ).then(function(builder) {
            // Exports the JSON representation of the dynamic form to that form we defined above
            document.getElementById('definition').value = JSON.stringify(builder.schema);
            
            builder.on('change', function (e) {
                // On change, update the above form w/ the latest dynamic form JSON
                document.getElementById('definition').value = JSON.stringify(builder.schema);
            })
        });;
      };
    </script>
  </head>
  <body>
    <div class="row">
        <div class="col-md-6">
            <h1>Form Builder Demo</h1>
        </div>
        
        <div class="col-md-6 text-right">
            <!-- This form holds the JSON form definition. -->
            <form method="post" action="{{ route('form-builder.store') }}">
                @csrf
                <input type="hidden" name="definition" id="definition" value="">
                <label for="">Form Name</label>
                <input type="text" name="form_name" class="form-control">
                <button type="submit" class="btn btn-outline-primary">
                    <i class="fas fa-save" aria-hidden="true"></i>
                    Save Form
                </button>        
        </div>
    </div>
    <div id="formio-builder"></div>
  </body>
</html>

resources/views/renderForm.blade.php
<html>
  <head>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdn.form.io/formiojs/formio.full.min.css'>
    <script src='https://cdn.form.io/formiojs/formio.full.min.js'></script>
   
  </head>
  <body>
<!-- form.blade.php -->

<div class="row">
    <div class="col-md-6">
        <h1>Form Builder Demo</h1>
    </div>
    
    <div class="col-md-6 text-right">
        <!-- This form holds the values the user has entered, as a JSON document. -->
        <form method="post" action="{{ route('form-builder.form_store') }}" id="submissionForm">
            @csrf
            
            <!-- State can be used to capture a Submit vs. Save Draft button -->
            <input type="hidden" name="state">
            <input type="hidden" name="form_builder_id" value="{{$form_builder_id}}">
            <!-- The JSON with all the values -->
            <input type="hidden" name="submissionValues" id="submissionValues" value="">
    </div>
</div>

<!-- Any server-side errors will be shown here. This is a fallback for when the client-side validations miss something. -->
@if ($errors->any())
<div class="alert alert-danger">
    <p style="font-size: 16pt"><strong>Oops</strong>, there was an issue with that.</p>
    <ul class="ml-5">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<!-- This becomes the builder. -->
<div id="formio-form"></div>

<script lang="text/javascript">
    window.onload = function() {
        Formio.createForm(document.getElementById('formio-form'), {!! $definition !!}).then(function (form) {
            form.submission = {
                data: {!! $data !!},
            };
            
            form.on('submit', function (submission) {
                var submitForm = document.getElementById('submissionForm');
                submitForm.querySelector('input[name=state]').value = submission.state;
                submitForm.querySelector('input[name=submissionValues]').value = JSON.stringify(submission.data);
                
                submitForm.submit();
            });
        });
    };
</script>
</body>
</html>